#!/bin/bash

usage() {
  echo "arguments:"
  echo "  -n namespace  the namespace that flux will be deployed into. Also the namespace flux will deploy to by default."
  exit 1
}

if (( $# == 0 )); then
  usage
fi

while getopts ':n:' opt; do 
  case ${opt} in
    n )
      export NAMESPACE=$OPTARG
      ;;
    \? )
      echo "Invalid option: $OPTARG" 1>&2
      exit 1
      ;;
    : )
      echo "Invalid option: $OPTARG requires an argument" 1>&2
      exit 1
      ;;
  esac
done

if [ -z "$NAMESPACE" ]; then
  echo "error: missing arg"
  usage
fi

cat k8s/*.yaml | envsubst
